- hosts: localhost
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition: "{{ lookup('template', 'service.yml') | from_yaml }}"
        validate_certs: no
        namespace: ethosverse
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: ethosverse
        definition: "{{ lookup('template', 'deployment.yml') | from_yaml }}"