apiVersion: v1
kind: Service
metadata:
  name: eapp-web-host-svc
  namespace: ethosverse
spec:
  selector:
    epod: eapp-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50601
      nodePort: 30010
    - name: mv-web-http
      protocol: TCP
      port: 30010
      targetPort: 50601