apiVersion: v1
kind: Service
metadata:
  name: eapp-web-host-svc
  namespace: ethosverse
spec:
  type: ClusterIP
  selector:
    epod: eapp-web
  ports:
    - name: mv-web-http
      protocol: TCP
      port: 80
      targetPort: 50601