apiVersion: v1
kind: Service
metadata:
  name: eapp-web-host-svc
  namespace: ethosverse
spec:
  selector:
    epod: eapp-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50601
      nodePort: 80
  type: NodePort