FROM ubuntu as builder

RUN apt update -y && \
	apt install -y wget bash curl file git unzip xz-utils zip nodejs npm

RUN wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz && \
	tar xf flutter_linux_3.24.0-stable.tar.xz && \
	rm flutter_linux_3.24.0-stable.tar.xz

ENV PATH="$PATH:/flutter/bin"

RUN git config --global --add safe.directory /flutter

RUN flutter doctor -v

RUN npm install -g firebase-tools 
COPY . .
#ARG PACKGAGES_READ_TOKEN="eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI4NTMwMWZiOS1mODU3LTRjYmQtYjkxOS1kMDMwYmY2NDIzY2UiLCJhdWQiOiI4NTMwMWZiOS1mODU3LTRjYmQtYjkxOS1kMDMwYmY2NDIzY2UiLCJvcmdEb21haW4iOiI1MGdyYW14IiwibmFtZSI6IkV0aG9zIEFwcHMgU2VydmljZSBDb250cmFjdHMiLCJpc3MiOiJodHRwczovLzUwZ3JhbXguamV0YnJhaW5zLnNwYWNlIiwicGVybV90b2tlbiI6IjFwN0t6QTBPS2pOQSIsInByaW5jaXBhbF90eXBlIjoiU0VSVklDRSIsImlhdCI6MTcyODAzNTcwMX0.Y6yDlqnJMioe5UgbmlBl6YnlgKptkYR8WnEHrTBKAtoPFfhGXMFOs6UGmI7eKqsCxpZesfPj454nCwv3WAxvXBlQCdX8YKmhBJqPEVqpLerShfQL6kkilWZA7VC-RdCxFeabreZsBrQoKJiFsmthPnD-Z6Ur0PcTdcAlg_ktsbM"


RUN cd fifty_gramx && flutter clean && dart pub token add https://dart.pkg.jetbrains.space/50gramx/p/main/dart-delivery/ --env-var="eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiI4NTMwMWZiOS1mODU3LTRjYmQtYjkxOS1kMDMwYmY2NDIzY2UiLCJhdWQiOiI4NTMwMWZiOS1mODU3LTRjYmQtYjkxOS1kMDMwYmY2NDIzY2UiLCJvcmdEb21haW4iOiI1MGdyYW14IiwibmFtZSI6IkV0aG9zIEFwcHMgU2VydmljZSBDb250cmFjdHMiLCJpc3MiOiJodHRwczovLzUwZ3JhbXguamV0YnJhaW5zLnNwYWNlIiwicGVybV90b2tlbiI6IjFwN0t6QTBPS2pOQSIsInByaW5jaXBhbF90eXBlIjoiU0VSVklDRSIsImlhdCI6MTcyODAzNTcwMX0.Y6yDlqnJMioe5UgbmlBl6YnlgKptkYR8WnEHrTBKAtoPFfhGXMFOs6UGmI7eKqsCxpZesfPj454nCwv3WAxvXBlQCdX8YKmhBJqPEVqpLerShfQL6kkilWZA7VC-RdCxFeabreZsBrQoKJiFsmthPnD-Z6Ur0PcTdcAlg_ktsbM"  && flutter pub get && flutter pub cache repair && flutter build web --dart-define=flavor=50.ethos.site --release 


# Use the official Nginx image as the base
FROM nginx:latest

#ARG JB_SPACE_FILE_SHARE_PATH
#ENV JB_SPACE_FILE_SHARE_PATH ${JB_SPACE_FILE_SHARE_PATH}

# Copy the built web application files into the Nginx content directory
#RUN echo "${JB_SPACE_FILE_SHARE_PATH}"
#RUN ls "${JB_SPACE_FILE_SHARE_PATH}"
#COPY "${JB_SPACE_FILE_SHARE_PATH}" /usr/share/nginx/html

COPY --from=builder fifty_gramx/build/web /usr/share/nginx/html 
# Expose the port on which Nginx will run
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
