# Use the official Nginx image as the base
FROM nginx:alpine

ARG JB_SPACE_FILE_SHARE_PATH
ENV JB_SPACE_FILE_SHARE_PATH ${JB_SPACE_FILE_SHARE_PATH}

# Copy the built web application files into the Nginx content directory
RUN echo "${JB_SPACE_FILE_SHARE_PATH}"
RUN ls "${JB_SPACE_FILE_SHARE_PATH}"
COPY "${JB_SPACE_FILE_SHARE_PATH}" /usr/share/nginx/html

# Expose the port on which Nginx will run
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
