
FROM ubuntu

RUN apt update -y && \
	apt install -y wget bash curl file git unzip xz-utils zip

RUN wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.6-stable.tar.xz && \
	tar xf flutter_linux_3.10.6-stable.tar.xz

RUN ls -l
RUN pwd
ENV PATH="$PATH:/flutter/bin"

RUN flutter doctor -v