// Objective-C API for talking to epod-nwk-xk Go package.
//   gobind -lang=objc epod-nwk-xk
//
// File is generated by gobind. Do not edit.

#ifndef __P2p_H__
#define __P2p_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class P2pPingArgs;
@class P2pPingReply;
@class P2pPingService;

@interface P2pPingArgs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable data;
@end

@interface P2pPingReply : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable data;
@end

@interface P2pPingService : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method PingService.Ping with unsupported parameter or return types

@end

FOUNDATION_EXPORT void P2pSayHello(void);

#endif
