
// Objective-C API for talking to the following Go packages
//
//	epod-nwk-xk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __P2p_FRAMEWORK_H__
#define __P2p_FRAMEWORK_H__

#include "P2p.objc.h"
#include "Universe.objc.h"

#endif
