// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPrTkBIPNHqYYAFepgno_QA2Lq2MAuPg',
    appId: '1:1048555807763:web:5c1e0a6f9cd7b38e40cbe6',
    messagingSenderId: '1048555807763',
    projectId: 'ethosverse-india',
    authDomain: 'ethosverse-india.firebaseapp.com',
    storageBucket: 'ethosverse-india.appspot.com',
    measurementId: 'G-PKH5LYECY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7yYXxIPP1QmegxaWscNqWvLDCFI73XkY',
    appId: '1:1048555807763:android:f30ab92102bfcb3740cbe6',
    messagingSenderId: '1048555807763',
    projectId: 'ethosverse-india',
    storageBucket: 'ethosverse-india.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2rqQHqw9dgedzB0zkRLlNcBbTMvKl6E',
    appId: '1:1048555807763:ios:c49421f1468b3dc340cbe6',
    messagingSenderId: '1048555807763',
    projectId: 'ethosverse-india',
    storageBucket: 'ethosverse-india.appspot.com',
    iosBundleId: 'com.fiftygramx.ethosai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS2rqQHqw9dgedzB0zkRLlNcBbTMvKl6E',
    appId: '1:1048555807763:ios:701fcc12bef6c05840cbe6',
    messagingSenderId: '1048555807763',
    projectId: 'ethosverse-india',
    storageBucket: 'ethosverse-india.appspot.com',
    iosBundleId: 'com.example.fiftyGramx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIPrTkBIPNHqYYAFepgno_QA2Lq2MAuPg',
    appId: '1:1048555807763:web:931d95f68df49c6d40cbe6',
    messagingSenderId: '1048555807763',
    projectId: 'ethosverse-india',
    authDomain: 'ethosverse-india.firebaseapp.com',
    storageBucket: 'ethosverse-india.appspot.com',
    measurementId: 'G-TRGMJE77RF',
  );

}