// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_70_ethos_nodes.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUYPGT5VwQPtGtr00xQjDISVrV8QCifNM',
    appId: '1:973163693894:web:326efc7e01b70b97194747',
    messagingSenderId: '973163693894',
    projectId: 'ethos-nodes',
    authDomain: 'ethos-nodes.firebaseapp.com',
    storageBucket: 'ethos-nodes.appspot.com',
    measurementId: 'G-DKCJW91SQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnaUM0ZMej1hNnIBOezR_w2Rt6cCqiOU',
    appId: '1:973163693894:android:ba83544dc480f0aa194747',
    messagingSenderId: '973163693894',
    projectId: 'ethos-nodes',
    storageBucket: 'ethos-nodes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCZkquDCG1QF8rHvY2pKdVZkWEZLDwxs',
    appId: '1:973163693894:ios:7f65d4956251afd0194747',
    messagingSenderId: '973163693894',
    projectId: 'ethos-nodes',
    storageBucket: 'ethos-nodes.appspot.com',
    iosBundleId: 'com.fiftygramx.seventy.zero.ethos.nodes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCZkquDCG1QF8rHvY2pKdVZkWEZLDwxs',
    appId: '1:973163693894:ios:7f65d4956251afd0194747',
    messagingSenderId: '973163693894',
    projectId: 'ethos-nodes',
    storageBucket: 'ethos-nodes.appspot.com',
    iosBundleId: 'com.fiftygramx.seventy.zero.ethos.nodes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUYPGT5VwQPtGtr00xQjDISVrV8QCifNM',
    appId: '1:973163693894:web:57e1cdfdd69e71d1194747',
    messagingSenderId: '973163693894',
    projectId: 'ethos-nodes',
    authDomain: 'ethos-nodes.firebaseapp.com',
    storageBucket: 'ethos-nodes.appspot.com',
    measurementId: 'G-TJS0KGFD9J',
  );

}