name: fifty_gramx
description: Your. Unified. Simple. Secure. Internet.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+60

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  shared_preferences: ^2.0.5
  firebase_core: 1.13.1
  firebase_messaging: 10.0.3
  overlay_support: ^1.2.1
  flutter_neumorphic:
    git:
      url: https://github.com/den0206/Flutter-Neumorphic.git
      ref: feature/remoce_accentcolor
  flutter_launcher_icons: ^0.9.0
  desktop_window: ^0.4.0
  flutter_feather_icons: ^2.0.0+1
  async: ^2.6.1
  bubble: ^1.2.1
  # dart_eval is an extensible bytecode compiler and runtime for the Dart language,
  # written in Dart, enabling dynamic codepush for Flutter and Dart AOT.
  dart_eval: ^0.4.6
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  flutter_switch: ^0.3.1
  rxdart: ^0.27.1
  http: ^0.13.3
  smooth_page_indicator: ^0.3.0-nullsafety.0
  file_picker: ^3.0.3
  in_app_purchase: ^1.0.6
  # A Flutter plugin for opening iOS and Android phone settings from an app.
  app_settings: ^4.1.1
  # A Flutter plugin to access and manage the device's contacts.
  contacts_service: ^0.6.1
  #  msix: ^2.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Get current device information from within the Flutter application.
  device_info_plus: ^4.1.2
  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^6.0.0
  # A Flutter plugin for finding commonly used locations on the filesystem. Supports Android, iOS,
  # Linux, macOS and Windows. Not all methods are supported on all platforms.


  path_provider: ^2.0.11
  # manages all the device level permissions
  permission_handler: ^8.1.2
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.12.3+2
  # A library that exposes device specific speech recognition capability.
  speech_to_text: ^4.2.2
  # A Dart package which parses total and available disk spaces on
  # Windows and UNIX-based systems (including Linux and macOS).

  # A parser for YAML.
  universal_disk_space: ^0.2.3
  yaml: 3.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "common-assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/certs/identityServer.crt
    - lib/assets/certs/conversationServer.crt
    - lib/assets/certs/knowledgeServer.crt
    # assets of 70GRAMx
    #   Ethos Pods
    #     Orchestrator Setup Scripts
    # 50 community eapp assets
    - lib/community/apps/gramx/fifty/zero/ethosapps.yaml
    - lib/community/apps/gramx/fifty/five/ethosapps.yaml
    # 50 ethos identity app assets
    - lib/community/apps/gramx/fifty/zero/ethos/identity/
    # 55 ethos eutopia app assets
    - lib/community/apps/gramx/fifty/five/ethos/eutopia/
    - lib/community/apps/gramx/seventy/zero/ethos/pods/configurations/orchestrator/setup/scripts/homebrew.sh
    - lib/community/apps/gramx/seventy/zero/ethos/pods/configurations/orchestrator/setup/scripts/install.sh
    - lib/community/apps/gramx/seventy/zero/ethos/pods/configurations/orchestrator/setup/scripts/installMultipass.sh
    #     multiverse resources
    #       cluster resources
    - lib/community/apps/gramx/seventy/zero/ethos/pods/configurations/multiverse/resources/cluster/
    #       namespaced resources
    - lib/community/apps/gramx/seventy/zero/ethos/pods/configurations/multiverse/resources/namespaced/
    #       persona resources
    - lib/community/apps/gramx/seventy/zero/ethos/pods/configurations/multiverse/resources/persona/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Black.ttf
          weight: 700
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Black.ttf
          weight: 800
        - asset: lib/community/apps/gramx/fifty/five/ethos/level/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: 50GRAMX
  publisher_display_name: Amit Khetan
  identity_name: 11781AppsHub.50GRAMX
  msix_version: 1.0.2.0
  #  certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  #  certificate_password: 1234 (require if using .pfx certificate)
  publisher: CN=D4AFB810-EF13-46E0-8839-A4A110696588
  #  logo_path: C:\<PathToIcon>\<Logo.png>
  #  start_menu_icon_path: C:\<PathToIcon>\<Icon.png>
  #  tile_icon_path: C:\<PathToIcon>\<Icon.png>
  #  vs_generated_images_folder_path: C:\<PathToFolder>\icons
  #  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient,microphone'